# SPDX-License-Identifier: MPL-2.0

version: 2

project_name: terraform-provider-llm

builds:
  - binary: terraform-provider-llm
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
      - s390x
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: freebsd
        goarch: s390x

archives:
  - formats: [zip]
    name_template: terraform-provider-llm_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - none*

checksum:
  name_template: terraform-provider-llm_{{ .Version }}_SHA256SUMS
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: ${artifact}.sig
    cmd: gpg
    args:
      - --batch
      - --local-user
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}

changelog:
  disable: true

release:
  extra_files:
    - glob: ./terraform-registry-manifest.json
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

snapshot:
  version_template: '{{ .Tag }}-next'
